# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0002_auto_20180821_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question1',
            new_name='Question_q',
        ),
    ]
